apiVersion: v1
kind: Pod
metadata:
   name: voting-app-pod
   labels:
        name: voting-app-pod
        app: demo-voting-app
spec:
    comtainers:
    - name: voting_app
      image: dockersamples/examplevotingapp_vote
      ports:
      - containerPort: 80
        

