apiVersion: v1
kind: Pod
metadata:
   name: worker-app-pod
   labels:
        name: worker-app-pod
        app: demo-voting-app
spec:
    comtainers:
    - name: worker_app
      image: dockersamples/examplevotingapp_worker


